# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import softhub.models.Application


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0002_developer_operatingsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('icon', models.ImageField(blank=True, upload_to=softhub.models.Application.upload_dir)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softhub.Developer')),
            ],
        ),
    ]
