# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0003_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_string', models.CharField(max_length=100)),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softhub.Application')),
            ],
        ),
    ]
