# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-02 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import softhub.models.Executable


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0004_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Executable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=200)),
                ('executable_file', models.FileField(upload_to=softhub.models.Executable.upload_dir)),
                ('release_platform', models.ManyToManyField(to='softhub.OperatingSystem')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_executable', to='softhub.Version')),
            ],
        ),
    ]
