# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0005_executable'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(choices=[('gpl', 'GPL'), ('gplv2', 'GPL v2'), ('gplv3', 'GPL v3'), ('mit', 'MIT'), ('apache', 'Apache'), ('closed source', 'Closed Source')], max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='version',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='softhub.License'),
        ),
    ]
