# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-29 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0006_auto_20170323_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='latest_version',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
