# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0007_version_latest_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executable',
            name='release_platform',
        ),
        migrations.AddField(
            model_name='executable',
            name='release_platform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='softhub.OperatingSystem'),
            preserve_default=False,
        ),
    ]
