# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0008_auto_20170402_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatingsystem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operatingsystem',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='family',
            field=models.CharField(choices=[('linux', 'Linux'), ('windows', 'Windows'), ('osx', 'OSx')], max_length=200, unique=True),
        ),
    ]
