# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0009_auto_20170404_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executable',
            name='release_platform',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='softhub.OperatingSystem'),
        ),
    ]
