# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0010_auto_20170404_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executable',
            name='release_platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softhub.OperatingSystem'),
        ),
    ]
