# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0013_auto_20170411_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
