# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 10:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import softhub.models.Application


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0014_auto_20170411_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='application',
            name='icon',
            field=models.ImageField(upload_to=softhub.models.Application.upload_dir),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softhub.Application'),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softhub.Rating'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
