# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-24 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softhub', '0015_auto_20170417_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
